// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-200]
	_ = x[RequestFail-101]
}

const (
	_ErrCode_name_0 = "请求失败"
	_ErrCode_name_1 = "success"
)

func (i ErrCode) String() string {
	switch {
	case i == 101:
		return _ErrCode_name_0
	case i == 200:
		return _ErrCode_name_1
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
