// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAssistantMember = "assistant_members"

// AssistantMember mapped from table <assistant_members>
type AssistantMember struct {
	ID             int64      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`
	ChannelID      int64      `gorm:"column:channel_id;type:int unsigned;not null;default:1" json:"channel_id"`  // 渠道id
	NickName       string     `gorm:"column:nick_name;type:varchar(255);not null" json:"nick_name"`              // 用户昵称
	Sex            int64      `gorm:"column:sex;type:tinyint;not null" json:"sex"`                               // 性别 男：1， 女：2
	MobilePhone    *string    `gorm:"column:mobile_phone;type:char(11)" json:"mobile_phone"`                     // 手机号
	VipStatus      int64      `gorm:"column:vip_status;type:tinyint;not null" json:"vip_status"`                 // 会员状态（0：非会员；1：会员；2到期）
	Rank           *int64     `gorm:"column:rank;type:tinyint" json:"rank"`                                      // 会员级别，0：普通用户，1：黄金会员， 2：白金会员
	Super          int64      `gorm:"column:super;type:tinyint;not null" json:"super"`                           // 0:非超级会员，1：超级会员
	IsSigned       *int64     `gorm:"column:is_signed;type:tinyint" json:"is_signed"`                            // 是否是微信自动续费签约用户
	VipEndAt       *time.Time `gorm:"column:vip_end_at;type:timestamp" json:"vip_end_at"`                        // 会员到期时间
	MemberStatus   int64      `gorm:"column:member_status;type:tinyint;not null;default:1" json:"member_status"` // 用户状态（0：注销；1：存活；2：违规）
	MemberPlatform *string    `gorm:"column:member_platform;type:varchar(10)" json:"member_platform"`            // 用户平台（WX：微信；QQ:腾讯QQ；WB：微博）
	WxName         *string    `gorm:"column:wx_name;type:varchar(255)" json:"wx_name"`
	Openid         *string    `gorm:"column:openid;type:char(28)" json:"openid"`          // 微信openid
	Follow         *int64     `gorm:"column:follow;type:tinyint" json:"follow"`           // 是否关注公众号, 0:未关注， 1:已关注
	Avatar         *string    `gorm:"column:avatar;type:varchar(255)" json:"avatar"`      // 微信用户头像
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"` // 注册时间
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp" json:"updated_at"` // 信息更新时间
}

// TableName AssistantMember's table name
// func (*AssistantMember) TableName() string {
// 	return TableNameAssistantMember
// }
