// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInventoryKey = "inventory_keys"

// InventoryKey mapped from table <inventory_keys>
type InventoryKey struct {
	ID           int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Secretkey    string     `gorm:"column:secretkey;type:text;not null;comment:秘钥或链接" json:"secretkey"`                      // 秘钥或链接
	Batch        string     `gorm:"column:batch;type:varchar(191);not null;comment:批次" json:"batch"`                         // 批次
	Username     *string    `gorm:"column:username;type:varchar(191);comment:用户名" json:"username"`                           // 用户名
	Password     *string    `gorm:"column:password;type:varchar(191);comment:密码" json:"password"`                            // 密码
	InventoryID  int64      `gorm:"column:inventory_id;type:int;not null;comment:库存id" json:"inventory_id"`                  // 库存id
	Status       int64      `gorm:"column:status;type:smallint;not null;default:1;comment:状态 1未出库 2已出库 3 已卖出" json:"status"` // 状态 1未出库 2已出库 3 已卖出
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp" json:"created_at"`
	OriSecretkey *string    `gorm:"column:ori_secretkey;type:varchar(191);comment:原始秘钥" json:"ori_secretkey"` // 原始秘钥
	InID         int64      `gorm:"column:in_id;type:int;not null;comment:后台入库用户id" json:"in_id"`             // 后台入库用户id
	OutID        int64      `gorm:"column:out_id;type:int;not null;comment:后台出库用户id" json:"out_id"`           // 后台出库用户id
	Des          *string    `gorm:"column:des;type:text" json:"des"`
	SaleTime     *time.Time `gorm:"column:sale_time;type:timestamp;comment:售出状态 1未售出 2已售出" json:"sale_time"`                          // 售出状态 1未售出 2已售出
	Supplier     *string    `gorm:"column:supplier;type:varchar(191);comment:供应商" json:"supplier"`                                    // 供应商
	IsRefund     int64      `gorm:"column:is_refund;type:tinyint;not null;default:1;comment:是否是退款入库链接/秘钥(1:不是，2：是)" json:"is_refund"` // 是否是退款入库链接/秘钥(1:不是，2：是)
	OutTime      *time.Time `gorm:"column:out_time;type:datetime;comment:出库时间" json:"out_time"`                                       // 出库时间
}

// TableName InventoryKey's table name
func (*InventoryKey) TableName() string {
	return TableNameInventoryKey
}
