// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOfficeOrder = "office_order"

// OfficeOrder mapped from table <office_order>
type OfficeOrder struct {
	ID                int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Token             string  `gorm:"column:token;type:varchar(32);not null;comment:订单标识" json:"token"`                                                   // 订单标识
	Rand              string  `gorm:"column:rand;type:varchar(4);not null;comment:随机字符串" json:"rand"`                                                     // 随机字符串
	Userid            int64   `gorm:"column:userid;type:int;not null;comment:用户id" json:"userid"`                                                         // 用户id
	Batch             *int64  `gorm:"column:batch;type:int;default:1;comment:用户购买购买次数，兼容二次购买" json:"batch"`                                               // 用户购买购买次数，兼容二次购买
	ChannelDealerID   int64   `gorm:"column:channel_dealer_id;type:int;not null;comment:渠道商id" json:"channel_dealer_id"`                                  // 渠道商id
	ChannelPackageID  int64   `gorm:"column:channel_package_id;type:int;not null;comment:渠道包id" json:"channel_package_id"`                                // 渠道包id
	ChannelID         *int64  `gorm:"column:channel_id;type:int;comment:渠道id" json:"channel_id"`                                                          // 渠道id
	UserChannelID     *int64  `gorm:"column:user_channel_id;type:int;comment:用户来源渠道id" json:"user_channel_id"`                                            // 用户来源渠道id
	BuyPosition       *string `gorm:"column:buy_position;type:varchar(32);default:downloader;comment:购买的位置 downloader下载器 desktop桌面版" json:"buy_position"` // 购买的位置 downloader下载器 desktop桌面版
	BuyMode           *string `gorm:"column:buy_mode;type:varchar(20);comment:订单所属用户的类型 wx：微信 email：邮箱 mobile：手机" json:"buy_mode"`                        // 订单所属用户的类型 wx：微信 email：邮箱 mobile：手机
	OrderNum          string  `gorm:"column:order_num;type:varchar(40);not null;comment:订单号" json:"order_num"`                                            // 订单号
	TransactionNum    *string `gorm:"column:transaction_num;type:varchar(40);comment:支付平台交易单号" json:"transaction_num"`                                    // 支付平台交易单号
	PayOrderNum       *string `gorm:"column:pay_order_num;type:varchar(255);comment:支付平台商户订单号" json:"pay_order_num"`                                      // 支付平台商户订单号
	Platform          *string `gorm:"column:platform;type:varchar(20);comment:支付平台：wx微信 ali支付宝" json:"platform"`                                          // 支付平台：wx微信 ali支付宝
	Price             float32 `gorm:"column:price;type:float(10,2);not null;comment:订单金额" json:"price"`                                                   // 订单金额
	ProductID         string  `gorm:"column:product_id;type:varchar(32);not null;comment:产品id" json:"product_id"`                                         // 产品id
	ProductName       string  `gorm:"column:product_name;type:varchar(255);not null;comment:产品名称" json:"product_name"`                                    // 产品名称
	RedeemCodeID      *int64  `gorm:"column:redeem_code_id;type:int;comment:活动兑换码id 没有为0" json:"redeem_code_id"`                                          // 活动兑换码id 没有为0
	Status            *int64  `gorm:"column:status;type:tinyint;default:1;comment:订单状态：1、未支付 2、已支付, -1 已退款, -2 退款申请中" json:"status"`                      // 订单状态：1、未支付 2、已支付, -1 已退款, -2 退款申请中
	PaymentTime       *int64  `gorm:"column:payment_time;type:int;comment:付款时间" json:"payment_time"`                                                      // 付款时间
	Secretkey         *string `gorm:"column:secretkey;type:varchar(255);comment:office激活密钥" json:"secretkey"`                                             // office激活密钥
	SecretkeyStatus   *int64  `gorm:"column:secretkey_status;type:tinyint;default:1;comment:密钥使用状态：1、未使用 2、已使用" json:"secretkey_status"`                  // 密钥使用状态：1、未使用 2、已使用
	ExpiryTime        *string `gorm:"column:expiry_time;type:varchar(20);comment:订单过期时间，产品有效期结束时间戳" json:"expiry_time"`                                   // 订单过期时间，产品有效期结束时间戳
	CreateAt          int64   `gorm:"column:create_at;type:int;not null;comment:创建时间" json:"create_at"`                                                   // 创建时间
	UpdateAt          *int64  `gorm:"column:update_at;type:int;comment:修改时间" json:"update_at"`                                                            // 修改时间
	OfficialAccountID *string `gorm:"column:official_account_id;type:varchar(255);comment:微信公众号ID" json:"official_account_id"`                            // 微信公众号ID
	Openid            *string `gorm:"column:openid;type:varchar(255);comment:用户openid" json:"openid"`                                                     // 用户openid
	PayAccount        *string `gorm:"column:pay_account;type:varchar(255);comment:支付商户ID" json:"pay_account"`                                             // 支付商户ID
	UUID              *string `gorm:"column:uuid;type:varchar(255);comment:设备标识" json:"uuid"`                                                             // 设备标识
	ClientVersion     *string `gorm:"column:client_version;type:varchar(255);comment:客户端版本" json:"client_version"`                                        // 客户端版本
	CCode             *string `gorm:"column:c_code;type:varchar(255);comment:渠道标识" json:"c_code"`                                                         // 渠道标识
}

// TableName OfficeOrder's table name
func (*OfficeOrder) TableName() string {
	return TableNameOfficeOrder
}
