application:
  domain: localhost:8008
  host: 0.0.0.0
  ishttps: false
  mode: develop
  name: office
  port: "8008"
  readtimeout: 2
  writertimeout: 1
database:
  dbtype: mysql
  #  host: 127.0.0.1
  host: 10.10.10.44
  name: office_v2
  #  password: ""
  password: "cumulon8888"
  port: "3306"
  username: root
  maxidleconn: 50
  maxopenconn: 25
  maxlifeseconds: 30
email:
  alias: office163
  host: smtp.163.com
  pass: your password
  port: 465
  user: fdevops@163.com
gorm:
  logmode: 0
jwt:
  secret: rWxBEuufQZl63EcOTJzbzXmJTDTxkRkAEeKF7wq0sfEyR5X9XC3KYvnh8DWBLKCx
  timeout: 86400
log:
  sql: 1
  compress: 2
  consolestdout: 1
  filestdout: 1
  level: debug
  localtime: 1
  maxage: 30
  maxbackups: 300
  maxsize: 64
  path: ./logs/office_client_
public:
  islocation: 0
redis:
  #  addr: 127.0.0.1:6379
  addr: 10.10.10.44:6379
  password:
  ## redis 中用到的库
  dbs: [1]
  prefix: ""
ssl:
  key: keystring
  pem: temp/pem.pem
news:
  fsurl: ""
elasticsearch:
  host: "http://10.10.10.44"
  port: "9200"
  scheme: "http"
  user: ""
  pass: ""
  debug: 1
