application:
  domain: localhost:8802
  host: 0.0.0.0
  ishttps: false
  mode: product
  name: office
  port: "8802"
  readtimeout: 1
  writertimeout: 2
database:
  dbtype: mysql
  host:
  name: "office"
  password:
  port: "3306"
  username: "office"
  maxidleconn: 50
  maxopenconn: 25
  maxlifeseconds: 30
email:
  alias: office
  host: smtp.163.com
  pass: your password
  port: 465
  user: fdevops@163.com
gorm:
  logmode: 0
  maxidleconn: 50
  maxopenconn: 25
  maxlifeseconds: 30
jwt:
  secret:
  timeout: 86400
log:
  sql: 1
  compress: 1
  consolestdout: 1
  filestdout: 1
  level: debug
  localtime: 1
  maxage: 30
  maxbackups: 300
  maxsize: 0.001
  path: /data/logs/go-assistant-desktop/office_client_
public:
  islocation: 0
redis:
  addr: "r-bp105q0tuvu0wyv8rj.redis.rds.aliyuncs.com:6379"
  password: "BAkeMm50jBthFC9a"
  db: 1
  db_prefix: "office_assistant_desktop_rdb:"
  cache_db: 0
  cache_prefix: "office_assistant_desktop_cache:"
ssl:
  key: keystrings
  pem: temp/pem.pem
news:
  fsurl: "https://open.feishu.cn/open-apis/bot/v2/hook/6d04948c-0dfd-4ef0-a2b2-bc27ebcb107a"
